routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/questions');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionController');
Route::resource('answers/question.answer', 'QuestionAnswerController');

resources/views/errors.blade.php
@if($errors->any())

    <div class="errors">

        @foreach($errors->all() as $error)

            <p class="alert alert-danger">{{ $error }}</p>

        @endforeach

    </div>

@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!

                    <div>
                        <a href="{{ route('questions.index') }}">I am ready to hear you, Bro</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection