routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/questions');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionController');
Route::resource('answers/question.answer', 'QuestionAnswerController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $guarded = [];

    public static $validators = [
        'content' => 'required|min:10|max:255',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(User::class);
    }
}

resources/views/answers/answers-list.blade.php
@if (count($answers))
    <hr/>
    <h5>last answers:</h5>
    <div>
        <table>
            @foreach($answers as $answer)
                <tr>
                    <td>
                        <a href="{{ route('question.answer.show', [
                            'question' => $question,
                            'answer' => $answer,
                        ]) }}">{{ mb_substr($answer->content, 0, 20) . '...' }}</a>
                    </td>
                    <td>
                        {{ ' ~ at: ' . ($answer->apdeted_at ?: $answer->created_at) . ' ~ ' }}
                    </td>
                    <td>
                        {{  'from:  ' . $answer->author->email}}
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endif

resources/views/answers/create.blade.php
@extends('layouts.questions-answers')

@section('content')
    <div>from: {{ $question->author->email }}</div>
    <h3>{{ $question->content }}</h3>

    <div class="btn-group">
        @if (\auth()->check() && \auth()->user()->can('update', $question))
            <a class="btn btn-primary" href="{{ route('questions.edit', ['question' => $question]) }}">
                edit question
            </a>
        @endif

        @if (\auth()->check() && \auth()->user()->can('delete', $question))
            <form method="post" action="{{ route('questions.destroy', ['question' => $question]) }}">

                @method('DELETE')
                @csrf

                <button class="btn btn-danger" type="submit">you can delete this question</button>
            </form>
        @endif
    </div>

    <hr/>

    <form method="post" action="{{ route('question.answer.store', ['question' => $question]) }}">

        @method('POST')
        @csrf

        <div>
            <label for="content">your answer bellow: </label>
        </div>
        <div>
            <textarea id="content" name="content" placeholder="write here anything...">{{ old('content') }}</textarea>
        </div>

        <hr/>
        @include('errors')

        <div>
            <button type="submit">push to add</button>
        </div>

    </form>

    @include('answers.answers-list', ['answers' => $question->answers])

@endsection

resources/views/answers/edit.blade.php
@extends('layouts.questions-answers')

@section('content')

    <div>
        question was: <h3>{{ $question->content }}</h3>
    </div>

    <hr/>

    <form method="post" action="{{ route('question.answer.update', [
        'question' => $question,
        'answer' => $answer,
    ]) }}">

        @method('PATCH')
        @csrf

        <div>
            <label for="content">меняй ОТВЕТ бля:</label>
        </div>
        <div>
            <textarea id="content"
                      name="content"
                      placeholder="че там, давай пиши сюда">{{ old('content') ?: $answer->content }}</textarea>
        </div>

        <hr/>
        @include('errors')

        <div>
            <button class="btn btn-primary" type="submit">change</button>
        </div>

    </form>

@endsection

resources/views/answers/show.blade.php
@extends('layouts.questions-answers')

@section('content')

    <h3>{{ $answer->content }}</h3>
    <div class="btn-group">

        @if (\auth()->check() && \auth()->user()->can('update', $answer))
            <div>
                <a class="btn btn-primary" href="{{ route('question.answer.edit', [
                'question' => $question,
                'answer' => $answer,
            ]) }}">edit</a>
            </div>
        @endif

        @if (\auth()->check() && \auth()->user()->can('delete', $answer))
            <div>
                <form method="post" action="{{ route('question.answer.destroy', [
                'question' => $question,
                'answer' => $answer,
            ]) }}">

                    @method('DELETE')
                    @csrf

                    <button class="btn btn-danger" type="submit">delete</button>
                </form>
            </div>
        @endif

    </div>
    <hr/>
    <div>author: {{ $answer->author->email }}</div>

@endsection