routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/questions');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionController');
Route::resource('answers/question.answer', 'QuestionAnswerController');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * Class Question
 * @package App
 * @property HasMany   answers
 * @property BelongsTo author
 */
class Question extends Model
{
    public static $validators = [
        'content' => 'required|min:10|max:255',
    ];

    protected $table = 'questions-for-users';

    protected $guarded = [];

    /**
     * @param array $validAnswer
     */
    public function addAnswer(array $validAnswer)
    {
        if (!array_key_exists('content', $validAnswer)) {
            throw new BadRequestHttpException('no answer data in request!');
        }

        $validAnswer = array_merge($validAnswer, [
            'question_id' => $this->getAttribute('id'),
            'author_id'   => auth()->id()
        ]);

        $this->answers()->create($validAnswer);
    }

    /**
     * @return HasMany
     */
    public function answers()
    {
        return $this->hasMany(Answer::class)
            ->orderBy('updated_at', 'desc')
            ->orderBy('created_at', 'desc');
    }

    /**
     * @return BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Exception;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;

class QuestionController extends Controller
{
    /**
     * QuestionController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('questions.index', [
            'questions' => Question::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Question::class);
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     * @throws ValidationException
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Question::class);

        $validated = $this->validate($request, Question::$validators);
        $validated['user_id'] = auth()->id();
        Question::create($validated);

        /* TODO
         * or this explicit way
         * $project = Project::create($validated);
        event(new ProjectCreated($project));
        */

        return redirect()->route('questions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Question $question
     * @return Response
     */
    public function show(Question $question)
    {
        return view('questions.show', ['question' => $question]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     * @return Response
     * @throws AuthorizationException
     */
    public function edit(Question $question)
    {
        $this->authorize('update', $question);
        return view('questions.edit', ['question' => $question]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request  $request
     * @param Question $question
     * @return Response
     * @throws AuthorizationException
     * @throws ValidationException
     */
    public function update(Request $request, Question $question)
    {
        $this->authorize('update', $question);
        $validated = $this->validate($request, Question::$validators);
        $question->update($validated);

        return redirect()->route('questions.show', ['question' => $question]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Question $question
     * @return Response
     * @throws AuthorizationException
     * @throws Exception
     */
    public function destroy(Question $question)
    {
        $this->authorize('delete', $question);

        $question->delete();
        return redirect()->route('questions.index');
    }
}

resources/views/questions/create.blade.php
@extends('layouts.questions-answers')

@section('content')
    <h1>Добавь вопрос по-братски</h1>

    <form method="post" action="{{ route('questions.store') }}">

        @method('POST')
        @csrf

        <div>
            <label for="content">сюда пиши вопрос: </label>
            <input id="content" name="content" placeholder="че ты?" value="{{ old('content') }}"/>
        </div>

        <div>
            <button type="submit">давай жми, вопрос добавим</button>
        </div>

        @include('errors')

    </form>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.questions-answers')

@section('content')

    <h1>{{ $question->content }}</h1>

    <form id="question-update" method="post" action="{{ route('questions.update', ['question' => $question]) }}">

        @method('PATCH')
        @csrf

        <div>
            <label for="content">меняй вопрос бля</label>
        </div>
        <div>
            <textarea id="content"
                      name="content"
                      placeholder="че там, давай пиши сюда">{{ old('content') ?: $question->content }}</textarea>
        </div>
    </form>

    @include('errors')

    <form id="question-delete" method="post" action="{{ route('questions.destroy', ['question' => $question]) }}">

        @method('DELETE')
        @csrf

    </form>

    <div class="btn-group">
        <button form="question-update" class="btn btn-primary" type="submit">change</button>
        <button form="question-delete" class="btn btn-danger" type="submit">delete this</button>
    </div>


@endsection

resources/views/questions/index.blade.php
@extends('layouts.questions-answers')

@section('content')

    @if (\auth()->check() && \auth()->user()->isAdmin())
        <a href="{{ route('questions.create') }}">this is a button to add a question</a>
        <hr/>
    @endif

    @if (!count($questions))
        <h3>there is not question yet, Bro</h3>
    @else
        <h5>popular:</h5>
        <hr/>
        <table>
            @foreach($questions as $question)

                <tr>
                    <td>
                        <a href="{{ route('question.answer.create', ['question' => $question]) }}">
                            {{ $question->content }}
                        </a>
                    </td>

                    <td>
                        <div>
                            @if (\auth()->check() && \auth()->user()->can('update', $question))
                                <a href="{{ route('questions.edit', ['question' => $question]) }}">
                                    === поправим вопрос ===
                                </a>
                            @else
                                <a href="{{ route('questions.show', ['question' => $question]) }}">
                                    === посмотреть ответы ===
                                </a>
                            @endif

                            @if ($question->answers->count())
                                ({{ $question->answers->count() }})
                            @endif
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
    @endif

@endsection

resources/views/questions/show.blade.php
@extends('layouts.questions-answers')

@section('content')

    <div>
        <h2> {{ $question->content }} </h2>
    </div>

    @if (\auth()->check() && \auth()->user()->can('update', $question))
        <div>
            <a href="{{ route('questions.edit', ['question' => $question]) }}">редактировать вопрос</a>
        </div>
    @endif

    <div>
        <a href="{{ route('question.answer.create', ['question' => $question]) }}">дать ответ!</a>
    </div>

    @include('answers.answers-list', ['answers' => $question->answers])

@endsection